### ISSUE TITLE
Change format of numbering of TOC

### ISSUE THREAD

**Issue by INOPIAE** [Flayms/Markdown2Pdf#44]
Currently the numbers in TOC are formatted like this:
Level 1 number
Level 2 small roman numbers
Level 3 - 6 small letters

Adjust formatting to have individual number formatting for each level
Adjust formatting to the following:
Level 1
Level 1.1
Level 1.1.1

**Comment by Flayms** [comment]
In general, this is up to the CSS styling of ordered lists. I am planning to bring in some changes though to make this more easily adjustable. 
Currently the TOC is created first as markdown and then converted to HTML. This needs to be changed so that the HTML gets directly created instead. Then more styling possibilities open up.

**Comment by INOPIAE** [comment]
I am looking forward to your changes.

**Comment by Flayms** [comment]
It's now settable with
```c#
options.TableOfContents.ListStyle  = ListStyle.Decimal;
```
