### ISSUE TITLE
Contributing Guide line

### ISSUE THREAD

**Issue by INOPIAE** [Flayms/Markdown2Pdf#49]
Are you sure that a new branch should be base on then develop branch.
For me this will lead to inconstitings branches.

**Comment by Flayms** [comment]
With a `main` and `dev` branch it's fairly common to branch from `dev`. It can make later merging easier because you already develop ontop of the other new code, rather than a potential stale `main`. Can't enforce this sadly so a `CONTRIBUTING.md` is the best alternative. See https://softwareengineering.stackexchange.com/questions/393422/git-branching-convention-baseline-from-dev-or-master .

**Comment by Flayms** [comment]
It's probably easier without develop branch so once i find some time for it, i will remove that one, so all PRs go directly into `main`

**Comment by Flayms** [comment]
resolved with #74
