### ISSUE TITLE
TOC don't work with cyrillic headers

### ISSUE THREAD

**Issue by ABatenev** [Flayms/Markdown2Pdf#73]
If I had header as 
`#Первый заголовок`
in TOC this header becomes unclickable, and page tracking is lost

**Comment by Flayms** [comment]
Seems like Markdig allows by default only ASCII-Characters for the header IDs (see https://github.com/xoofx/markdig/issues/95).
I am going to change the default behaviour of Markdown2Pdf here like described in the issue. This probably shouldn't cause any additional problems since chrome supports HTML5.

**Comment by ABatenev** [comment]
Super! May I know when this will be available via nuget?

**Comment by Flayms** [comment]
👍 Gonna publish a new version soon, will remind you then

**Comment by Flayms** [comment]
https://github.com/Flayms/Markdown2Pdf/releases/tag/v2.1.0
